name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  IMAGE: bg

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${REGION}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/bg-images/${{ env.IMAGE }}:${{ github.sha }}
          no-cache: true

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy binary-garden \
          --image gcr.io/${{ secrets.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }} \
          --port=3000 \
          --region ${{ secrets.PROJECT_REGION }} \
          --allow-unauthenticated \
          --service-account ${{ secrets.PROJECT_SERVICE_ACCOUNT }}  \
          --set-secrets=EMAILJS_SERVICE_ID=EMAILJS_SERVICE_ID:1,EMAILJS_TEMPLATE_ID=EMAILJS_TEMPLATE_ID:1,EMAILJS_PUBLIC_KEY=EMAILJS_PUBLIC_KEY:1,EMAILJS_PRIVATE_KEY=EMAILJS_PRIVATE_KEY:1
